sudo: false
language: elixir

cache:
  directories:
    - _build
    - deps
script:
  - mix test
  - if [[ `elixir -v` = *"1.8"* ]]; then mix format --check-formatted; fi
  - if [[ `elixir -v` = *"1.8"* ]]; then
      travis_wait 30 mix dialyzer --halt-exit-status --format term;
    fi
matrix:
  include:
    - elixir: 1.6
      otp_release: 19.3
    - elixir: 1.6
      otp_release: 20.3
    - elixir: 1.6
      otp_release: 21.0
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.7
      otp_release: 21.0
    - elixir: 1.8
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 21.0
    - elixir: 1.8
      otp_release: 22.1
    - elixir: 1.9
      otp_release: 20.3
    - elixir: 1.9
      otp_release: 21.0
    - elixir: 1.9
      otp_release: 22.1
    - elixir: 1.10
      otp_release: 20.3
    - elixir: 1.10
      otp_release: 21.0
    - elixir: 1.10
      otp_release: 22.1
